### ISSUE TITLE
id 类特征重编码后 为什么 效果和 one hot相当？

### ISSUE THREAD

**Issue by BigHeartC** [YouChouNoBB/ijcai-18-top2-single-mole-solution#2]
> id 类特征重编码,直接当作特征,树模型深度设置-1,避免了 onehot 大量占用内存空间,实际效果和 onehot 相当。

耀神，请问你经验分享里上面这句话怎么理解，为什么重新编码后就可以达到one hot的效果？

**Comment by BigHeartC** [comment]
谢谢解惑，lgb里可以声明categorical feature，那ID类特征重编码后是否有必要声明他们为categorical feature？我尝试过几次，结果都是不声明的时候好，请问这是什么原因？

**Comment by YouChouNoBB** [comment]
不清楚，可能不同数据效果不一样

**Comment by BigHeartC** [comment]
好的！十分感谢~
